---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: data
  labels:
    type: local
spec:
  capacity:
    storage: 49Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/tmp/data"

---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: model
  labels:
    type: local
spec:
  capacity:
    storage: 49Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/tmp/model"

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mydata
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 49Gi

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mymodels
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 49Gi

---
apiVersion: v1
kind: Pod
metadata:
  name: dataaccess
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: data
      mountPath: "/data"
    - name: models
      mountPath: "/model"
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: mydata
  - name: models
    persistentVolumeClaim:
      claimName: mymodels